language: elixir
elixir:
  - "1.2.5"
  - "1.3.2"
otp_release:
  - 18.1
sudo: false
env:
  MIX_ENV=test
before_script:
  - mix deps.get --only test
script:
  - mix test
  - mix credo
  - mix coveralls
